# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Frontend - Next.js Dashboard
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    reviewers:
      - "matejlecnik"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      radix:
        patterns:
          - "@radix-ui/*"
      tanstack:
        patterns:
          - "@tanstack/*"
      dev-dependencies:
        dependency-type: "development"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Backend - Python FastAPI
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    reviewers:
      - "matejlecnik"
    groups:
      fastapi:
        patterns:
          - "fastapi*"
          - "uvicorn*"
          - "pydantic*"
      supabase:
        patterns:
          - "supabase*"
          - "postgrest*"
          - "gotrue*"
      scrapers:
        patterns:
          - "*praw*"
          - "httpx*"
          - "aiohttp*"
    ignore:
      # Ignore updates that might break compatibility
      - dependency-name: "supabase"
        update-types: ["version-update:semver-major"]
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "02:00"
    open-pull-requests-limit: 3
    target-branch: "main"
    labels:
      - "dependencies"
      - "ci/cd"
      - "automated"
    reviewers:
      - "matejlecnik"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Docker (if using Docker images)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    target-branch: "main"
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    reviewers:
      - "matejlecnik"
    ignore:
      # Ignore minor/patch updates for base images
      - dependency-name: "node"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
      - dependency-name: "python"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    commit-message:
      prefix: "build"
      include: "scope"

# Security updates configuration
# These are created immediately regardless of schedule
registries:
  npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org
    username: "${{ secrets.NPM_USERNAME }}"
    password: "${{ secrets.NPM_TOKEN }}"