version: '3.8'

# Docker Compose configuration for Hetzner Worker Servers
# Runs Instagram scraper workers that pull jobs from Redis queue

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: b9-worker-${WORKER_ID:-1}
    restart: unless-stopped
    environment:
      # Supabase
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}

      # OpenAI
      - OPENAI_API_KEY=${OPENAI_API_KEY}

      # RapidAPI
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}

      # Cloudflare R2
      - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - ENABLE_R2_STORAGE=true

      # Worker Config
      - WORKER_ID=${WORKER_ID:-1}
      - ENVIRONMENT=production
      - LOG_LEVEL=info

      # Redis Queue (points to API server)
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./logs:/app/logs
    networks:
      - b9-network
    healthcheck:
      test: ["CMD", "ps", "aux", "|", "grep", "worker.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  b9-network:
    driver: bridge
