name: Deploy to Vercel (b9-dashboard)

on:
  push:
    branches: [ main ]
    paths:
      - 'dashboard_development/b9-dashboard/**'
      - '.github/workflows/vercel_deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    defaults:
      run:
        working-directory: dashboard_development/b9-dashboard
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard_development/b9-dashboard/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Pull Vercel Environment Information
        run: npx vercel pull --yes --environment=production --token=${{ env.VERCEL_TOKEN }}

      - name: Deploy (Remote build on Vercel)
        run: npx vercel --prod --token=${{ env.VERCEL_TOKEN }}


